services:
  - type: web
    name: eventplatform-api
    env: docker
    dockerfilePath: ./EventPlatform.API/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:80
      - key: DOTNET_RUNNING_IN_CONTAINER
        value: true
    healthCheckPath: /api/events
    autoDeploy: true 